const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{Платформер: 0},
	{СледитьЗа: 0},
	{Спрайт: 0},
	{Твёрдый: 0},
	{Спрайт2: 0},
	{ТайловыйФон: 0},
	{Спрайт5: 0},
	{Якорь: 0},
	{Текст: 0},
	{Синусоида: 0},
	{Спрайт6: 0},
	{nomer: 0},
	{Прикрепить: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Текст2: 0},
	{Клавиатура: 0},
	{ТайловыйФон2: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Текст3: 0},
	{d9ea23ed4c95163b9976022b49e3d: 0},
	{ТайловыйФон3: 0},
	{Текст4: 0},
	{Текст5: 0},
	{Угасание: 0},
	{Спрайт7: 0},
	{Аудио: 0},
	{fraza: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	Клавиатура: class extends self.IInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	d9ea23ed4c95163b9976022b49e3d: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Текст4: class extends self.ITextInstance {},
	Текст5: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {}
}